name: Build Demos
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '8-2018-q4'
      - name: Clean the build environment
        working-directory: demos/base/ARM_CORTEXM_ST_Nucleo_F091RC/GCC
        run: make TOOL_PATH= clean
      - name: Build the demo applications
        working-directory: demos/base/ARM_CORTEXM_ST_Nucleo_F091RC/GCC
        run: make -j TOOL_PATH= all
